log_level: debug
log_file: application/logs/myapp.log
http_listen:
  port: 8080
  ip: 0.0.0.0
grpc_listen:
  port: 50051
  ip: 0.0.0.0
database:
  host: postgres
  port: 5432
  user: myuser
  password: mypassword
  dbname: mydatabase
  sslmode: disable
rabbit:
  user: guest
  password: guest
  host: rabbitmq
  port: 5672
  queue_name: calendar_events
