global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: sender
    static_configs:
      - targets: ["sender:9002"]
  - job_name: api
    static_configs:
      - targets: ["api:9001"]